apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: kutt
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: kutt
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "kutt-role"
          serviceAccountRef:
            name: "vault-auth"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kutt-secrets-sync
  namespace: kutt
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: kutt-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: kutt-secrets
        property: db-password
    - secretKey: JWT_SECRET
      remoteRef:
        key: kutt-secrets
        property: jwt-secret
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: kutt-secrets
        property: oidc-client-secret
