apiVersion: apps/v1
kind: Deployment
metadata:
  name: kutt-redis
  namespace: kutt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kutt-redis
  template:
    metadata:
      labels:
        app: kutt-redis
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: redis
          image: redis:7.2-alpine
          args: ["redis-server", "--save", "", "--appendonly", "no"]
          ports:
            - containerPort: 6379
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
            runAsNonRoot: true
            runAsUser: 999
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 25m
              memory: 64Mi
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kutt-redis
  namespace: kutt
spec:
  selector:
    app: kutt-redis
  ports:
    - port: 6379
      targetPort: 6379
