apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: deemix-oauth2-proxy-creds
  namespace: navidrome
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: deemix-oauth2-proxy-creds
    creationPolicy: Owner
  data:
    - secretKey: cookie-secret
      remoteRef:
        key: navidrome-secrets
        property: cookie_secret
    - secretKey: client-secret
      remoteRef:
        key: deemix-secrets
        property: client_secret
