apiVersion: v1
kind: PersistentVolume
metadata:
  name: deemix-config-pv
  annotations: { argocd.argoproj.io/sync-wave: "-5" }
spec:
  capacity: { storage: 1Gi }
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: truenas-nfs
  mountOptions: ["nfsvers=4.1", "hard"]
  nfs:
    server: "10.0.60.10"
    path: "/mnt/data/k8s-cluster/pvc-volumes/deemix-config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deemix-config-pvc
  namespace: navidrome
  annotations: { argocd.argoproj.io/sync-wave: "-5" }
spec:
  storageClassName: truenas-nfs
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 1Gi } }
  volumeName: deemix-config-pv
