apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: navidrome
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: navidrome
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "navidrome-role"
          serviceAccountRef:
            name: "vault-auth"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: navidrome-oauth2-proxy-creds
  namespace: navidrome
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: navidrome-oauth2-proxy-creds
    creationPolicy: Owner
  data:
    - secretKey: cookie-secret
      remoteRef:
        key: navidrome-secrets
        property: cookie_secret
    - secretKey: client-secret
      remoteRef:
        key: navidrome-secrets
        property: client_secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: navidrome-lyrics-fetcher-creds
  namespace: navidrome
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: navidrome-lyrics-fetcher-creds
    creationPolicy: Owner
  data:
    - secretKey: subsonic-user
      remoteRef:
        key: navidrome-secrets
        property: subsonic_user
    - secretKey: subsonic-pass
      remoteRef:
        key: navidrome-secrets
        property: subsonic_pass
