apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - external-secrets.yaml
  - baseline-network-policy.yaml
  - oauth2-proxy.yaml
  - deemix-storage.yaml
  - deemix-external-secrets.yaml
  - deemix.yaml
  - deemix-ingress.yaml
  - storage.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ingress-web.yaml
  - middlewares.yaml
  - redirect-service.yaml
  - policy.yaml
  - subwave-storage.yaml
  - subwave.yaml
  - subwave-entrypoint.yaml
  - subwave-ingress.yaml
  - subwave-policy.yaml
