apiVersion: v1
kind: ConfigMap
metadata:
  name: radicale-config
  namespace: radicale
data:
  config.template: |
    [server]
    hosts = 0.0.0.0:5232

    [auth]
    type = oauth2
    oauth2_token_endpoint = https://auth.foobarbaz.fr/realms/foobarbaz/protocol/openid-connect/token
    oauth2_client_id = ${CLIENT_ID}
    oauth2_client_secret = ${CLIENT_SECRET}

    [storage]
    filesystem_folder = /data/collections

    [rights]
    type = authenticated

  rights: |
    # Temporairement désactivé
