# 3. Synchronize Radicale Secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radicale-secrets-sync
  namespace: radicale
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: radicale-oauth2-creds
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: radicale-oauth2-creds
        property: client_id
    - secretKey: client-secret
      remoteRef:
        key: radicale-oauth2-creds
        property: client_secret
