apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: audit-unsigned-third-party-images
  annotations:
    policies.kyverno.io/title: Audit Unsigned Third Party Images
    policies.kyverno.io/category: Software Supply Chain Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      Audit unsigned third party images before enforcing repository-wide signature checks.
spec:
  admission: true
  emitWarning: false
  validationFailureAction: Audit
  webhookTimeoutSeconds: 30
  failurePolicy: Ignore
  background: false
  rules:
    - name: audit-third-party-signatures
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - cilium-system
                - kyverno
                - trivy-system
      skipBackgroundRequests: true
      verifyImages:
        - imageReferences:
            - "*"
          skipImageReferences:
            - ghcr.io/ripitchip/*
          mutateDigest: false
          verifyDigest: false
          useCache: true
          required: false
          attestors:
            - count: 1
              entries:
                - keyless:
                    issuer: https://token.actions.githubusercontent.com
                    subjectRegExp: ^https://github.com/.+/.github/workflows/.+
                    rekor:
                      url: https://rekor.sigstore.dev
                  signatureAlgorithm: sha256
