apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-owned-image-signatures
  annotations:
    policies.kyverno.io/title: Verify Owned Image Signatures
    policies.kyverno.io/category: Software Supply Chain Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >-
      Require keyless Cosign signatures for images published under ghcr.io/ripitchip.
spec:
  admission: true
  emitWarning: false
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  background: false
  rules:
    - name: verify-ghcr-ripitchip-keyless-signature
      match:
        any:
          - resources:
              kinds:
                - Pod
      skipBackgroundRequests: true
      verifyImages:
        - imageReferences:
            - ghcr.io/ripitchip/*
          mutateDigest: true
          verifyDigest: true
          useCache: true
          required: true
          attestors:
            - count: 1
              entries:
                - keyless:
                    issuer: https://token.actions.githubusercontent.com
                    subjectRegExp: ^https://github.com/ripitchip/.+/.github/workflows/.+@refs/heads/main$
                    rekor:
                      url: https://rekor.sigstore.dev
                  signatureAlgorithm: sha256
