apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: mimir
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: mimir
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "mimir-role"
          serviceAccountRef:
            name: "vault-auth"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mimir-alertmanager-smtp
  namespace: mimir
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: mimir-alertmanager-smtp
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: smtp-from
      remoteRef:
        key: mailrise
        property: smtp-from
    - secretKey: smtp-host
      remoteRef:
        key: mailrise
        property: smtp-host
    - secretKey: smtp-password
      remoteRef:
        key: mailrise
        property: smtp-password
    - secretKey: smtp-port
      remoteRef:
        key: mailrise
        property: smtp-port
    - secretKey: smtp-user
      remoteRef:
        key: mailrise
        property: smtp-user
