apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: mimir-distributed
    targetRevision: 5.3.0
    helm:
      values: |
        deploymentMode: monolithic
        mimir:
          structuredConfig:
            multitenancy_enabled: false
            common:
              storage:
                backend: filesystem
            blocks_storage:
              backend: filesystem
              filesystem:
                dir: /mimir-storage/blocks
            alertmanager_storage:
              backend: filesystem
              filesystem:
                dir: /mimir-storage/alerts
            ruler_storage:
              backend: filesystem
              filesystem:
                dir: /mimir-storage/rules
        
        ingester:
          replicas: 1
          podSecurityContext:
            runAsUser: 11985
            runAsGroup: 11985
            fsGroup: 11985
            runAsNonRoot: true
          containerSecurityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 11985
        querier:
          replicas: 1
          podSecurityContext:
            runAsUser: 11985
            runAsGroup: 11985
            fsGroup: 11985
            runAsNonRoot: true
          containerSecurityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 11985
        distributor:
          replicas: 1
          podSecurityContext:
            runAsUser: 11985
            runAsGroup: 11985
            fsGroup: 11985
            runAsNonRoot: true
          containerSecurityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 11985

        # Sub-charts configuration
        minio:
          enabled: true
          makeBucketsJob:
            enabled: false
          buckets:
            - name: mimir-tsdb
            - name: mimir-ruler
            - name: enterprise-metrics-tsdb
            - name: enterprise-metrics-admin
            - name: enterprise-metrics-ruler
          # Official MinIO chart uses 'securityContext' for Pod level
          securityContext:
            enabled: true
            runAsUser: 11985
            runAsGroup: 11985
            fsGroup: 11985
            runAsNonRoot: true
          # Official MinIO chart uses 'containerSecurityContext' for Container level
          containerSecurityContext:
            enabled: true
            runAsNonRoot: true
            runAsUser: 11985
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

        # Key for this dependency is rollout_operator (underscore)
        rollout_operator:
          enabled: true
          podSecurityContext:
            runAsUser: 11985
            runAsGroup: 11985
            fsGroup: 11985
            runAsNonRoot: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 11985

        nginx:
          enabled: true
          podSecurityContext:
            runAsUser: 11985
            runAsGroup: 11985
            fsGroup: 11985
            runAsNonRoot: true
          containerSecurityContext:
            runAsNonRoot: true
            runAsUser: 11985
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true

        ruler:
          podSecurityContext:
            runAsUser: 11985
            runAsGroup: 11985
            fsGroup: 11985
            runAsNonRoot: true
          containerSecurityContext:
            runAsNonRoot: true
            runAsUser: 11985
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
        
        compactor:
          podSecurityContext:
            runAsUser: 11985
            runAsGroup: 11985
            fsGroup: 11985
            runAsNonRoot: true
          containerSecurityContext:
            runAsNonRoot: true
            runAsUser: 11985
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true

        store_gateway:
          podSecurityContext:
            runAsUser: 11985
            runAsGroup: 11985
            fsGroup: 11985
            runAsNonRoot: true
          containerSecurityContext:
            runAsNonRoot: true
            runAsUser: 11985
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true

        alertmanager:
          podSecurityContext:
            runAsUser: 11985
            runAsGroup: 11985
            fsGroup: 11985
            runAsNonRoot: true
          containerSecurityContext:
            runAsNonRoot: true
            runAsUser: 11985
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true

        query_frontend:
          podSecurityContext:
            runAsUser: 11985
            runAsGroup: 11985
            fsGroup: 11985
            runAsNonRoot: true
          containerSecurityContext:
            runAsNonRoot: true
            runAsUser: 11985
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true

        query_scheduler:
          podSecurityContext:
            runAsUser: 11985
            runAsGroup: 11985
            fsGroup: 11985
            runAsNonRoot: true
          containerSecurityContext:
            runAsNonRoot: true
            runAsUser: 11985
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true

        overrides_exporter:
          podSecurityContext:
            runAsUser: 11985
            runAsGroup: 11985
            fsGroup: 11985
            runAsNonRoot: true
          containerSecurityContext:
            runAsNonRoot: true
            runAsUser: 11985
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true

        rbac:
          podSecurityContext:
            runAsUser: 11985
            runAsGroup: 11985
            fsGroup: 11985
            runAsNonRoot: true
        
        # Default Pod Security Context for remaining components
        podSecurityContext:
          runAsUser: 11985
          runAsGroup: 11985
          fsGroup: 11985
          runAsNonRoot: true
        
        # Default Container Security Context for remaining components
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 11985
        
        mimir-continuous-test:
          enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mimir
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
