apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/ripitchip/gitops-argocd.git"
    targetRevision: HEAD
    path: infrastructure/01-system/mimir/manifests
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mimir
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: batch
      kind: Job
      name: mimir-make-minio-buckets-5.0.14
      jsonPointers:
        - /spec
