apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vault-security-core
  namespace: vault
spec:
  podSelector: { matchLabels: { app.kubernetes.io/name: vault } }
  policyTypes: [Ingress, Egress]
  ingress:
    - from: [{ podSelector: {} }] # Raft clustering
    - from:
        - namespaceSelector:
            matchLabels: { kubernetes.io/metadata.name: auth }
        - namespaceSelector:
            matchLabels: { kubernetes.io/metadata.name: pass }
        - namespaceSelector:
            matchLabels: { kubernetes.io/metadata.name: external-secrets }
        - namespaceSelector:
            matchLabels: { kubernetes.io/metadata.name: traefik }
      ports:
        - { protocol: TCP, port: 8200 }
        - { protocol: TCP, port: 8201 }
  egress:
    - to: [{ podSelector: {} }]
    # DNS
    - to:
        - namespaceSelector:
            matchLabels: { kubernetes.io/metadata.name: kube-system }
      ports: [{ protocol: UDP, port: 53 }, { protocol: TCP, port: 53 }]
    # API KUBERNETES (Crucial pour la validation des tokens)
    - to:
        - ipBlock: { cidr: 10.96.0.0/12 }
      ports:
        - { protocol: TCP, port: 443 }
        - { protocol: TCP, port: 6443 }