apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - external-secrets.yaml
  - storage.yaml
  - policy.yaml
  - app.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: iam-stack
    includeSelectors: true
