apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: auth-security-hardened
  namespace: auth
spec:
  endpointSelector: {}
  ingress:
    # 1. Allow all internal traffic within the 'auth' namespace
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": auth
    # 2. Allow Ingress from Traefik (Keycloak + ACME Solver) and Vault
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: traefik
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
            - port: "8089"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: vault
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": cloudreve
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
  egress:
    # 1. Allow all internal traffic within the 'auth' namespace
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": auth
    # 2. Kubernetes API access
    - toEntities:
        - kube-apiserver
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: argocd
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": vault
      toPorts:
        - ports:
            - port: "8200"
              protocol: TCP
    # 3. Email Egress (OVH SMTP)
    - toFQDNs:
        - matchName: "ssl0.ovh.net"
      toPorts:
        - ports:
            - port: "465"
              protocol: TCP

