apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: policy-reporter-egress
  namespace: policy-reporter
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: policy-reporter
  egress:
    # 1. Kubernetes API access to read reports
    - toEntities:
        - kube-apiserver
    # 2. DNS Resolution
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: policy-reporter-ui-ingress
  namespace: policy-reporter
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: policy-reporter-ui
  ingress:
    # Allow OAuth2 Proxy to access UI
    - fromEndpoints:
        - matchLabels:
            k8s-app: oauth2-proxy-policy-reporter
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
  egress:
    # 1. Access to the backend
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: policy-reporter
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    # 2. Kubernetes API access
    - toEntities:
        - kube-apiserver
    # 3. DNS Resolution
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
