apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: poll
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: poll
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "poll-role"
          serviceAccountRef:
            name: "vault-auth"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: poll-secrets-sync
  namespace: poll
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: poll-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        NEXT_MONGODB_URI: "mongodb://{{ .mongodb_root_username }}:{{ .mongodb_root_password }}@poll-mongodb:27017/{{ .mongodb_database }}?authSource=admin"
        MONGO_INITDB_ROOT_USERNAME: "{{ .mongodb_root_username }}"
        MONGO_INITDB_ROOT_PASSWORD: "{{ .mongodb_root_password }}"
        MONGO_INITDB_DATABASE: "{{ .mongodb_database }}"
  data:
    - secretKey: mongodb_root_username
      remoteRef:
        key: poll-secrets
        property: mongodb-root-username
    - secretKey: mongodb_root_password
      remoteRef:
        key: poll-secrets
        property: mongodb-root-password
    - secretKey: mongodb_database
      remoteRef:
        key: poll-secrets
        property: mongodb-database
    - secretKey: NEXT_PUBLIC_ENCRYPTION_KEY
      remoteRef:
        key: poll-secrets
        property: encryption-key
    - secretKey: NEXT_PUBLIC_ENCRYPTION_IV
      remoteRef:
        key: poll-secrets
        property: encryption-iv
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: poll-secrets
        property: oidc-client-secret
