apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - database.yaml
  - configmap.yaml
  - external-secrets.yaml
  - baseline-network-policy.yaml
  - policy.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
