apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hugo-blog
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  rules:
  - host: foobarbaz.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hugo-blog
            port:
              number: 80
  tls:
  - hosts:
    - foobarbaz.fr
    secretName: hugo-blog-main-tls
