apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: blog-redirect-https@kubernetescrd, blog-add-trailing-slash@kubernetescrd, blog-redirect-blog-to-root@kubernetescrd
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  rules:
  - host: foobarbaz.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blog
            port:
              number: 80
  tls:
  - hosts:
    - foobarbaz.fr
    secretName: blog-main-tls
