apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingvin-share
  namespace: pingvin-share
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingvin-share
  template:
    metadata:
      labels:
        app: pingvin-share
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 19582
        runAsGroup: 19582
        fsGroup: 19582
      containers:
        - name: pingvin-share
          image: ghcr.io/smp46/pingvin-share-x:v1.19.1
          ports:
            - containerPort: 3000
          env:
            - name: TRUST_PROXY
              value: "true"
            - name: PORT
              value: "8080"
            - name: APP_URL
              value: "https://share.foobarbaz.fr"
            - name: OIDC_ENABLED
              value: "true"
            - name: OIDC_CLIENT_ID
              value: "share"
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: pingvin-share-secrets
                  key: OIDC_CLIENT_SECRET
            - name: OIDC_ISSUER
              value: "https://auth.foobarbaz.fr/realms/master"
            - name: OIDC_NAME
              value: "Keycloak"
          volumeMounts:
            - name: storage
              mountPath: /opt/app/backend/data
              subPath: pingvin-share/data
            - name: storage
              mountPath: /opt/app/frontend/public/img
              subPath: pingvin-share/images
            - name: config-file
              mountPath: /opt/app/backend/data/config.yaml
              subPath: config.yaml
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: pingvin-share-pvc
        - name: config-file
          configMap:
            name: pingvin-share-config
