apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingvin-share
  namespace: pingvin-share
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingvin-share
  template:
    metadata:
      labels:
        app: pingvin-share
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 19582
        runAsGroup: 19582
        fsGroup: 19582
      containers:
        - name: pingvin-share
          image: ghcr.io/smp46/pingvin-share-x:v1.19.1
          ports:
            - containerPort: 3000
          env:
            - name: TRUST_PROXY
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /opt/app/backend/data
            - name: images
              mountPath: /opt/app/frontend/public/img
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pingvin-share-data-pvc
        - name: images
          persistentVolumeClaim:
            claimName: pingvin-share-images-pvc
