apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingvin-share
  namespace: pingvin-share
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: pingvin-share-public-chain@kubernetescrd
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  rules:
  - host: share.foobarbaz.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pingvin-share
            port:
              number: 80
  tls:
  - hosts:
    - share.foobarbaz.fr
    secretName: pingvin-share-tls
