apiVersion: apps/v1
kind: Deployment
metadata:
  name: baikal
  namespace: baikal
  labels:
    app: baikal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baikal
  template:
    metadata:
      labels:
        app: baikal
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 57238
        fsGroup: 57238
      initContainers:
        - name: prepare-baikal
          image: ghcr.io/aalmenar/baikal:0.11.1
          command: ["sh", "-c", "cp -rp /var/www/baikal/* /mnt/baikal/ && chown -R 57238:57238 /mnt/baikal/"]
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
          volumeMounts:
            - name: baikal-full-dir
              mountPath: /mnt/baikal
        - name: fix-pvc-permissions
          image: busybox:1.36
          command: ["sh", "-c", "chown -R 57238:57238 /var/www/baikal/Specific"]
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
          volumeMounts:
            - name: data
              mountPath: /var/www/baikal/Specific
      containers:
        - name: baikal
          image: ghcr.io/aalmenar/baikal:0.11.1
          command: ["sh", "-c"]
          args:
            - |
              /usr/sbin/php-fpm8.5 -F -d listen=127.0.0.1:9000 -d pid=/tmp/php-fpm.pid &
              nginx -g 'daemon off;'
          env:
            - name: BAIKAL_SKIP_CHOWN
              value: "1"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            runAsUser: 57238
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: baikal-full-dir
              mountPath: /var/www/baikal
            - name: data
              mountPath: /var/www/baikal/Specific
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: nginx-run
              mountPath: /var/run
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-lib
              mountPath: /var/lib/nginx
            - name: nginx-log
              mountPath: /var/log/nginx
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: baikal-data-pvc
        - name: baikal-full-dir
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: baikal-nginx-conf
        - name: nginx-run
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-lib
          emptyDir: {}
        - name: nginx-log
          emptyDir: {}
