apiVersion: v1
kind: ConfigMap
metadata:
  name: baikal-nginx-conf
  namespace: baikal
data:
  default.conf: |
    server {
      listen 8080;
      listen [::]:8080;
      server_name _;

      root   /var/www/baikal/html;
      index index.php;

      rewrite ^/.well-known/caldav /dav.php redirect;
      rewrite ^/.well-known/carddav /dav.php redirect;

      charset utf-8;

      location ~ /(\.ht|Core|Specific) {
        deny all;
        return 404;
      }

      location ~ ^(.+\.php)(.*)$ {
        try_files $fastcgi_script_name =404;
        include        /etc/nginx/fastcgi_params;
        fastcgi_split_path_info  ^(.+\.php)(.*)$;
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        fastcgi_param  PATH_INFO        $fastcgi_path_info;
      }

      location ~ /.ht {
        deny all;
      }
    }
