apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crafty-security-headers
  namespace: minecraft
spec:
  headers:
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    stsPreload: true
    forceSTSHeader: true
    contentTypeNosniff: true
    browserXssFilter: true
    referrerPolicy: strict-origin-when-cross-origin
    permissionsPolicy: camera=(), microphone=(), geolocation=()
    customRequestHeaders:
      X-Forwarded-Proto: https
    frameDeny: true
    contentSecurityPolicy: 'default-src ''self'' ''unsafe-inline'' ''unsafe-eval'';
      img-src ''self'' data: https:;'
    customResponseHeaders:
      Cross-Origin-Opener-Policy: same-origin
      Cross-Origin-Resource-Policy: same-origin
      Cross-Origin-Embedder-Policy: require-corp
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crafty-compress
  namespace: minecraft
spec:
  compress: {}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crafty-chain
  namespace: minecraft
spec:
  chain:
    middlewares:
    - name: crafty-security-headers
    - name: crafty-compress
