apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crafty
  namespace: minecraft
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: minecraft-crafty-chain@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts: [minecraft.foobarbaz.fr]
      secretName: crafty-tls
  rules:
    - host: minecraft.foobarbaz.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crafty
                port:
                  number: 8000
