apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
  annotations:
    metallb.io/loadBalancerIPs: "10.0.50.201"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: minecraft
  ports:
    - name: minecraft
      port: 25565
      targetPort: minecraft
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: crafty
  namespace: minecraft
spec:
  type: ClusterIP
  selector:
    app: minecraft
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
