apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: startpage
  namespace: startpage
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: startpage-public-chain@kubernetescrd
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  rules:
    - host: apps.foobarbaz.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: startpage
                port:
                  number: 80
  tls:
    - hosts:
        - apps.foobarbaz.fr
      secretName: startpage-tls
