apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: karakeep
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: karakeep
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "karakeep-role"
          serviceAccountRef:
            name: "vault-auth"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-secrets-sync
  namespace: karakeep
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: karakeep-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        NEXTAUTH_SECRET: "{{ .nextauth_secret }}"
        OAUTH_CLIENT_SECRET: "{{ .oauth_client_secret }}"
        MEILI_MASTER_KEY: "{{ .meili_master_key }}"
  data:
    - secretKey: nextauth_secret
      remoteRef:
        key: link-secrets
        property: nextauth-secret
    - secretKey: oauth_client_secret
      remoteRef:
        key: link-secrets
        property: keycloak-client-secret
    - secretKey: meili_master_key
      remoteRef:
        key: link-secrets
        property: meili-master-key
