apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations.ignoreDifferences.external-secrets.io_ExternalSecret: |
    jqPathExpressions:
      - .spec.data[]?.remoteRef.conversionStrategy
      - .spec.data[]?.remoteRef.decodingStrategy
      - .spec.data[]?.remoteRef.metadataPolicy
      - .spec.data[]?.remoteRef.nullBytePolicy
      - .spec.target.creationPolicy
      - .spec.target.deletionPolicy
      - .spec.target.template.engineVersion
      - .spec.target.template.mergePolicy
