apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: argocd-policy
  namespace: argocd
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - {}
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": traefik
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": alloy
  egress:
    - toEntities:
        - kube-apiserver
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    - toFQDNs:
        - matchName: "auth.foobarbaz.fr"
    - toEntities:
        - world
        - host
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "80"
              protocol: TCP
    - toEndpoints:
        - {}
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": auth
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": external-secrets
