apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: external-secrets-hardened
  namespace: external-secrets
spec:
  endpointSelector: {}
  ingress:
    # 1. Controller to Webhook
    - fromEndpoints:
        - {}
    # 2. Webhook
    - fromEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "9443"
              protocol: TCP
            - port: "10250"
              protocol: TCP
  egress:
    # 1. Internal Namespace
    - toEndpoints:
        - {}
    # 2. DNS
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    # 3. Vault
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: vault
      toPorts:
        - ports:
            - port: "8200"
              protocol: TCP
    # 4. API Kubernetes
    - toEntities:
        - kube-apiserver