apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: external-secrets-core
  namespace: external-secrets
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
  ingress:
    - from: [podSelector: {}] # Internal webhook communication
  egress:
    - to: [podSelector: {}]
    - to:
        - namespaceSelector:
            matchLabels: { kubernetes.io/metadata.name: kube-system }
      ports: [{ protocol: UDP, port: 53 }, { protocol: TCP, port: 53 }]
    - to:
        - namespaceSelector:
            matchLabels: { kubernetes.io/metadata.name: vault }
      ports: [{ protocol: TCP, port: 8200 }]
    - to: # Access to K8s API (Internal + External)
        - ipBlock: { cidr: 0.0.0.0/0 }
        - ipBlock: { cidr: 10.96.0.0/12 } # Standard K8s Service range
      ports: 
        - { protocol: TCP, port: 443 }
        - { protocol: TCP, port: 6443 }