apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: 'https://charts.external-secrets.io'
    chart: external-secrets
    targetRevision: 2.4.1
    helm:
      values: |
        installCRDs: true
        podSecurityContext:
          enabled: true
          runAsUser: 4712
          runAsGroup: 4712
          fsGroup: 4712
        securityContext:
          enabled: true
          runAsNonRoot: true
          runAsUser: 4712
          runAsGroup: 4712
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        webhook:
          podSecurityContext:
            enabled: true
            runAsUser: 5823
            runAsGroup: 5823
            fsGroup: 5823
          securityContext:
            enabled: true
            runAsNonRoot: true
            runAsUser: 5823
            runAsGroup: 5823
          lookaheadInterval: 5m
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
        certController:
          podSecurityContext:
            enabled: true
            runAsUser: 6934
            runAsGroup: 6934
            fsGroup: 6934
          securityContext:
            enabled: true
            runAsNonRoot: true
            runAsUser: 6934
            runAsGroup: 6934
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
