apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: immich
data:
  # Core
  IMMICH_VERSION: v3.0.2
  NODE_ENV: production
  TZ: Europe/Paris
  
  # Database
  DB_HOSTNAME: immich-postgres
  DB_USERNAME: immich
  DB_DATABASE_NAME: immich
  
  # Redis
  REDIS_HOSTNAME: immich-redis
  
  # Services
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003
  UPLOAD_LOCATION: /usr/src/app/upload
  
  # Network
  IMMICH_HOST: 0.0.0.0
  IMMICH_PORT: "2283"
  
  # Logging
  LOG_LEVEL: info

  # OIDC
  IMMICH_OAUTH_ENABLED: "true"
  IMMICH_OAUTH_ISSUER_URL: "https://auth.foobarbaz.fr/realms/foobarbaz"
  IMMICH_OAUTH_CLIENT_ID: "immich"
  IMMICH_OAUTH_AUTO_REGISTER: "true"
  IMMICH_OAUTH_BUTTON_TEXT: "Login with Keycloak"
  IMMICH_OAUTH_SCOPE: "openid email profile"
