apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: immich
data:
  DB_HOSTNAME: immich-postgres
  DB_USERNAME: immich
  DB_DATABASE_NAME: immich
  REDIS_HOSTNAME: immich-redis
  IMMICH_VERSION: v1.105.1
---
apiVersion: v1
kind: Secret
metadata:
  name: immich-secrets
  namespace: immich
type: Opaque
data:
  # immichpass en base64
  DB_PASSWORD: aW1taWNocGFzcw==
