apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-postgres
  namespace: immich
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: immich-postgres
  template:
    metadata:
      labels:
        app: immich-postgres
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 15432
        runAsGroup: 15432
        fsGroup: 15432
      containers:
        - name: postgres
          image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
          env:
            - name: POSTGRES_USER
              valueFrom: { configMapKeyRef: { name: immich-config, key: DB_USERNAME } }
            - name: POSTGRES_DB
              valueFrom: { configMapKeyRef: { name: immich-config, key: DB_DATABASE_NAME } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: immich-secrets, key: DB_PASSWORD } }
            - name: POSTGRES_INITDB_ARGS
              value: "--data-checksums"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            limits:
              cpu: "1"
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
            runAsNonRoot: true
            runAsUser: 15432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {} # On passera en PVC TrueNAS après
---
apiVersion: v1
kind: Service
metadata:
  name: immich-postgres
  namespace: immich
spec:
  selector:
    app: immich-postgres
  ports:
    - port: 5432
      targetPort: 5432
