apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "immich-role"
          serviceAccountRef:
            name: "vault-auth"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-secrets-sync
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: immich-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: immich-secrets
        property: db-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: immich-secrets
        property: oidc-client-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: immich-secrets
        property: redis-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
