apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storage.yaml
  - external-secrets.yaml
  - config.yaml
  - baseline-network-policy.yaml
  - policy.yaml
  - database.yaml
  - redis.yaml
  - server.yaml
  - ml.yaml
  - ingress.yaml
