apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 15433
        runAsGroup: 15433
        fsGroup: 15433
      containers:
        - name: server
          image: ghcr.io/immich-app/immich-server:v1.105.1
          envFrom:
            - configMapRef: { name: immich-config }
          env:
            - name: DB_PASSWORD
              valueFrom: { secretKeyRef: { name: immich-secrets, key: DB_PASSWORD } }
          ports:
            - containerPort: 2283
          volumeMounts:
            - name: library
              mountPath: /data
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
            runAsNonRoot: true
            runAsUser: 15433
      volumes:
        - name: library
          persistentVolumeClaim: { claimName: immich-library-pvc }
---
apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: immich
spec:
  selector:
    app: immich-server
  ports:
    - port: 2283
      targetPort: 2283
