apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: tempo
    targetRevision: 1.10.1
    helm:
      values: |
        tempo:
          repository: grafana/tempo
          tag: 2.4.1
          multitenancyEnabled: false
          reportingEnabled: false
          metricsGenerator:
            enabled: true
            storage:
              path: /var/tempo/metrics-generator
            traces_storage:
              path: /var/tempo/generator-traces
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          storage:
            trace:
              backend: local
              local:
                path: /var/tempo/traces
              wal:
                path: /var/tempo/wal
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 12906
            runAsGroup: 12906

        builder:
          replicas: 1

        securityContext:
          runAsNonRoot: true
          runAsUser: 12906
          runAsGroup: 12906
        
        persistence:
          enabled: true
          storageClassName: truenas-nfs
          accessModes:
            - ReadWriteOnce
          size: 50Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tempo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
