apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: tempo
    targetRevision: 1.10.1
    helm:
      values: |
        tempo:
          repository: grafana/tempo
          tag: 2.4.1
          multitenancy_enabled: false
          reporting_enabled: false
          metrics_generator_enabled: true
        
        storage:
          trace:
            backend: local
            local:
              path: /var/tempo/traces
            wal:
              path: /var/tempo/wal

        builder:
          replicas: 1

        # Security Context to comply with Kyverno policies
        podSecurityContext:
          fsGroup: 12906
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 12906
          runAsGroup: 12906
        
        persistence:
          enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tempo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
