apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crowdsec-bouncer
  namespace: crowdsec
spec:
  plugin:
    crowdsec-bouncer:
      enabled: true
      crowdsecMode: live
      crowdsecLapiKey: "dec458e3ca2f3922f5d72f10b89b6576"
      crowdsecLapiScheme: "http"
      crowdsecLapiHost: "crowdsec-service.crowdsec.svc.cluster.local:8080"
