apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-bouncer-key
  namespace: crowdsec
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
type: Opaque
data:
  # Base64 encoded key for crowdsec bouncer plugin: dec458e3ca2f3922f5d72f10b89b6576
  bouncer-key: ZGVjNDU4ZTNjYTJmMzkyMmY1ZDcyZjEwYjg5YjY1NzY=
