apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    chart: immich
    repoURL: ghcr.io/immich-app/immich-charts
    targetRevision: 0.12.0
    helm:
      values: |
        image:
          tag: v1.105.1

        # Configuration d'Immich (Persistence)
        immich:
          persistence:
            library:
              existingClaim: immich-library-pvc

        # Ingress (Nouveau format 0.12.0)
        server:
          ingress:
            main:
              enabled: true
              ingressClassName: traefik
              annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                cert-manager.io/cluster-issuer: "letsencrypt-prod"
              hosts:
                - host: photo.foobarbaz.fr
                  paths:
                    - path: /
              tls:
                - hosts:
                    - photo.foobarbaz.fr
                  secretName: photo-tls

        # Base de données et Redis via Variables d'Environnement
        controllers:
          main:
            containers:
              main:
                env:
                  DB_HOSTNAME: immich-postgres
                  DB_USERNAME: immich
                  DB_DATABASE_NAME: immich
                  DB_PASSWORD: immichpass
                  REDIS_HOSTNAME: immich-valkey

        # Activation du nouveau subchart Valkey (remplace Redis)
        valkey:
          enabled: true
          persistence:
            data:
              enabled: true
              size: 1Gi
              type: emptyDir # On passera en PVC après validation
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
