apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: icons
  namespace: icons
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: icons-public-chain@kubernetescrd
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  rules:
    - host: icon.foobarbaz.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: icons
                port:
                  number: 80
  tls:
    - hosts:
        - icon.foobarbaz.fr
      secretName: icons-tls
