apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: icons-isolation
  namespace: icons
spec:
  endpointSelector:
    matchLabels:
      app: icons
  ingress:
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": traefik
            "k8s:app.kubernetes.io/name": traefik
      toPorts:
        - ports:
            - port: "4050"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": alloy
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: icons-sync-egress
  namespace: icons
spec:
  endpointSelector:
    matchLabels:
      app: icons-sync
  egress:
    - toFQDNs:
        - matchName: "github.com"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
