apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-operator-exceptions
  namespace: trivy-system
  labels:
    trivy-operator.policy.configaudit: "true"
data:
  # Exception pour CoreDNS (Seccomp AVD-KSV-0117 / KSV117)
  exception_coredns.rego: |
    package builtin.kubernetes.KSV117

    exception[rules] {
        input.metadata.namespace == "kube-system"
        startswith(input.metadata.name, "coredns")
        rules := [""]
    }

  # Exception pour "Runs As Root" (AVD-KSV-0012 / KSV012)
  # Pour les initContainers spécifiques
  exception_init_root.rego: |
    package builtin.kubernetes.KSV012

    exception[rules] {
        some i
        input.spec.initContainers[i].name == "fix-permissions"
        rules := [""]
    }

    exception[rules] {
        some i
        input.spec.initContainers[i].name == "prepare-lib"
        rules := [""]
    }
