apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    chart: vault
    targetRevision: 0.28.0
    helm:
      values: |
        server:
          extraInitContainers:
            - name: fix-permissions
              image: busybox
              command: ["sh", "-c", "chown -R 100:1000 /vault/data && chmod -R 700 /vault/data"]
              volumeMounts:
                - name: data
                  mountPath: /vault/data

          standalone:
            enabled: true
            config: |
              ui = true
              listener "tcp" {
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
              }
              storage "raft" {
                path = "/vault/data"
                node_id = "vault-0"
              }

          dataStorage:
            enabled: false

          extraVolumes:
            - name: data
              persistentVolumeClaim:
                claimName: data-vault-0

          extraVolumeMounts:
            - name: data
              mountPath: "/vault/data"

          ingress:
            enabled: true
            ingressClassName: "traefik"
            hosts:
              - host: "vault.foobarbaz.fr"
                paths: ["/"]
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
            tls:
              - secretName: vault-tls-cert
                hosts:
                  - "vault.foobarbaz.fr"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vault
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true