resources:
  - cilium/release.yaml
  - cilium/l2-policy.yaml
  - external-secrets
  - vault/vault-app-definition.yaml
  - argocd
  - cert-manager
  - kyverno
  - grafana/grafana-app-definition.yaml
  - alloy/alloy-app-definition.yaml
  - loki/loki-app-definition.yaml
  - hubble/app-definition.yaml


