resources:
  - cilium/release.yaml
  - external-secrets
  - vault
  - argocd
  - cert-manager
  - kyverno
  - trivy
  - trivy-adapter
  - hubble/app-definition.yaml
  - policy-reporter/policy-reporter-app-definition.yaml
