apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: policy-reporter-ingress
  namespace: policy-reporter
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: policy-reporter-public-chain@kubernetescrd
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  rules:
  - host: policy-reporter.foobarbaz.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: policy-reporter-oauth2-proxy
            port:
              number: 80
  tls:
  - hosts:
    - policy-reporter.foobarbaz.fr
    secretName: policy-reporter-tls
