apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: policy-reporter-ingress
  namespace: policy-reporter
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    ingress.cilium.io/loadbalancer-mode: "shared"
spec:
  ingressClassName: cilium
  rules:
  - host: policy-reporter.foobarbaz.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: policy-reporter-oauth2-proxy
            port:
              number: 80
  tls:
  - hosts:
    - policy-reporter.foobarbaz.fr
    secretName: policy-reporter-tls
