apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy-policy-reporter
  namespace: policy-reporter
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy-policy-reporter
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy-policy-reporter
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 5678
        runAsGroup: 5678
        fsGroup: 5678
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 5678
            runAsGroup: 5678
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          args:
            - --provider=oidc
            - --oidc-issuer-url=https://auth.foobarbaz.fr/realms/master
            - --email-domain=*
            - --http-address=0.0.0.0:4180
            - --upstream=http://policy-reporter-ui.policy-reporter.svc.cluster.local:8080
            - --cookie-secure=true
            - --cookie-samesite=lax
            - --set-authorization-header=true
            - --pass-access-token=true
            - --redirect-url=https://policy-reporter.foobarbaz.fr/oauth2/callback
            - --insecure-oidc-skip-issuer-verification=true
            - --reverse-proxy=true
            - --allowed-group=policy-reporter-admin
            - --scope=openid profile email groups
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-policy-reporter
                  key: client-id
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-policy-reporter
                  key: client-secret
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-policy-reporter
                  key: cookie-secret
          ports:
            - containerPort: 4180
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-policy-reporter
  namespace: policy-reporter
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: oauth2-proxy-policy-reporter
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: policy-reporter-ingress
  namespace: policy-reporter
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  rules:
  - host: policy-reporter.foobarbaz.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy-policy-reporter
            port:
              number: 80
  tls:
  - hosts:
    - policy-reporter.foobarbaz.fr
    secretName: policy-reporter-tls
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-policy-reporter-secrets
  namespace: policy-reporter
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-policy-reporter
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: client-id
    remoteRef:
      key: oauth2-proxy
      property: policy-reporter_client_id
  - secretKey: client-secret
    remoteRef:
      key: oauth2-proxy
      property: policy-reporter_client_secret
  - secretKey: cookie-secret
    remoteRef:
      key: oauth2-proxy
      property: cookie_secret
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: oauth2-proxy-policy-reporter-policy
  namespace: policy-reporter
spec:
  endpointSelector:
    matchLabels:
      k8s-app: oauth2-proxy-policy-reporter
  ingress:
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": traefik
            "k8s:app.kubernetes.io/name": traefik
      toPorts:
        - ports:
            - port: "4180"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": policy-reporter
            "app.kubernetes.io/name": policy-reporter-ui
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
