apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    chart: cilium
    repoURL: https://helm.cilium.io/
    targetRevision: 1.19.4
    helm:
      values: |
        prometheus:
          enabled: true
          port: 9962

        hubble:
          enabled: true
          metrics:
            enabled:
              - dns:query;labelsContext=source_ip,source_namespace,source_pod,destination_ip,destination_namespace,destination_pod,query,return_code
              - drop
              - tcp
              - flow
              - icmp
              - http
            serviceMonitor:
              enabled: false # We use Alloy, so we don't need ServiceMonitors
          relay:
            enabled: true
            resources:
              limits:
                cpu: 200m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi

        envoy:
          enabled: true
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi

        operator:
          enabled: true
          prometheus:
            enabled: true
            port: 9963
          clusterPoolIPv4PodCIDRList:
          - 10.244.0.0/16
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
