apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: default
  source:
    chart: cilium
    repoURL: https://helm.cilium.io/
    targetRevision: 1.19.4
    helm:
      values: |
        securityContext:
          capabilities:
            ciliumAgent:
              - CHOWN
              - DAC_OVERRIDE
              - FOWNER
              - IPC_LOCK
              - KILL
              - NET_ADMIN
              - NET_RAW
              - SETGID
              - SETUID
              - SYS_ADMIN
              - SYS_RESOURCE
              - SYS_PTRACE
              - SYS_CHROOT
              - SETFCAP
            cleanCiliumState:
              - NET_ADMIN
              - SYS_ADMIN
              - SYS_RESOURCE


        l2announcements:
          enabled: true

        ingressController:
          enabled: true
          default: true
          loadBalancer:
            l2:
              enabled: true
          service:
            annotations:
              io.cilium/lb-ipam-ips: "10.0.50.200"

        prometheus:
          enabled: true
          port: 9962

        hubble:
          enabled: true
          metrics:
            enabled:
              - dns
              - drop
              - tcp
              - flow
              - icmp
              - http
            serviceMonitor:
              enabled: false # We use Alloy, so we don't need ServiceMonitors
          relay:
            enabled: true
            resources:
              limits:
                cpu: 200m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi

        envoy:
          enabled: true
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi

        operator:
          enabled: true
          prometheus:
            enabled: true
            port: 9963
          clusterPoolIPv4PodCIDRList:
          - 10.244.0.0/16
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
