apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    chart: cilium
    repoURL: https://helm.cilium.io/
    targetRevision: 1.19.4
    helm:
      values: |
        commonAnnotations:
          trivy-operator.aquasecurity.github.io/trivy-ignore-checks: "AVD-KSV-0037"
        hubble:
          enabled: true
          relay:
            enabled: true
          ui:
            enabled: false
        operator:
          clusterPoolIPv4PodCIDRList:
          - 10.244.0.0/16
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
