apiVersion: v1
kind: PersistentVolume
metadata:
  name: sure-storage-pv
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: truenas-nfs
  mountOptions:
    - nfsvers=4.1
    - hard
  nfs:
    server: "10.0.60.10"
    path: "/mnt/data/k8s-cluster/pvc-volumes/sure-storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sure-storage-pvc
  namespace: sure
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  storageClassName: truenas-nfs
  volumeName: sure-storage-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sure-db-pv
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: truenas-nfs
  mountOptions:
    - nfsvers=4.1
    - hard
  nfs:
    server: "10.0.60.10"
    path: "/mnt/data/k8s-cluster/pvc-volumes/sure-db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sure-db-pvc
  namespace: sure
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  storageClassName: truenas-nfs
  volumeName: sure-db-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sure-redis-pv
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: truenas-nfs
  mountOptions:
    - nfsvers=4.1
    - hard
  nfs:
    server: "10.0.60.10"
    path: "/mnt/data/k8s-cluster/pvc-volumes/sure-redis"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sure-redis-pvc
  namespace: sure
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  storageClassName: truenas-nfs
  volumeName: sure-redis-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
