apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://aquasecurity.github.io/helm-charts/'
    chart: trivy-operator
    targetRevision: 0.32.1
    helm:
      values: |
        targetNamespaces: ""
        excludeNamespaces: "kube-*,argo*"
        trivy:
          ignoreUnfixed: true
          skipCheckIDs: "KSV009,KSV017,KSV021,KSV037,KSV117,AVD-KSV-0117"
          configAudit:
            skipCheckIDs: "KSV009,AVD-KSV-0009,KSV117,AVD-KSV-0117"
        trivyOperator:

            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 512Mi
        trivyOperator:
          scanJobTolerations:
            - operator: Exists
        operator:
          scanJobTimeout: 5m
          clusterComplianceEnabled: false
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
        nodeCollector:
          tolerations:
            - operator: Exists
        serviceMonitor:
          enabled: false
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 65534
          fsGroup: 65534
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        trivyOperator:
          scanJobPodTemplatePodSecurityContext:
            runAsNonRoot: true
            runAsUser: 10000
            fsGroup: 10000
          scanJobPodTemplateContainerSecurityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10000
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: trivy-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
