apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nightingale
  namespace: nightingale
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: nightingale-public-chain@kubernetescrd
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  rules:
    - host: karaoke.foobarbaz.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nightingale
                port:
                  number: 80
  tls:
    - hosts:
        - karaoke.foobarbaz.fr
      secretName: nightingale-tls
