apiVersion: v1
kind: PersistentVolume
metadata:
  name: nightingale-data-pv
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: truenas-nfs
  mountOptions:
    - nfsvers=4.1
    - hard
  nfs:
    server: "10.0.60.10"
    path: "/mnt/data/k8s-cluster/pvc-volumes/nightingale-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nightingale-data-pvc
  namespace: nightingale
spec:
  storageClassName: truenas-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  volumeName: nightingale-data-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nightingale-music-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: truenas-nfs
  mountOptions:
    - nfsvers=4.1
    - hard
    - ro
  nfs:
    server: "10.0.60.10"
    path: "/mnt/data/k8s-cluster/pvc-volumes/navidrome-music"
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nightingale-music-pvc
  namespace: nightingale
spec:
  storageClassName: truenas-nfs
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nightingale-music-pv
