apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencloud
  namespace: opencloud
  labels:
    app: opencloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencloud
  template:
    metadata:
      labels:
        app: opencloud
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 62403
        runAsGroup: 62403
        fsGroup: 62403
      containers:
        - name: opencloud
          image: opencloudeu/opencloud:7.2.4
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 62403
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: OC_URL
              value: "https://drive.tomlab.fr"
            - name: OC_INSECURE
              value: "true"
            - name: PROXY_HTTP_ADDR
              value: "0.0.0.0:9200"
            - name: PROXY_TLS
              value: "false"
            - name: OC_LOG_LEVEL
              value: "info"
            - name: OC_ADMIN_USER
              value: "admin"
            - name: OC_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opencloud-secrets
                  key: ADMIN_PASSWORD
                  optional: true
            - name: IDM_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opencloud-secrets
                  key: ADMIN_PASSWORD
                  optional: true
          ports:
            - containerPort: 9200
              name: http
          readinessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 10
            periodSeconds: 20
          volumeMounts:
            - name: data
              mountPath: /var/lib/opencloud
            - name: config
              mountPath: /etc/opencloud
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: opencloud-data-pvc
        - name: config
          emptyDir: {}
