apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: opencloud
spec:
  headers:
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    stsPreload: true
    forceSTSHeader: true
    contentTypeNosniff: true
    browserXssFilter: true
    referrerPolicy: strict-origin-when-cross-origin
    permissionsPolicy: camera=(), microphone=(), geolocation=()
    customFrameHeaders:
      X-Frame-Options: "SAMEORIGIN"
    contentSecurityPolicy: 'default-src ''self'' ''unsafe-inline'' ''unsafe-eval''; img-src ''self'' data: https:; connect-src ''self'' https://auth.foobarbaz.fr https://drive.tomlab.fr; frame-src ''self'' https://auth.foobarbaz.fr; frame-ancestors ''self'' https://*.foobarbaz.fr https://*.tomlab.fr;'
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rate-limit
  namespace: opencloud
spec:
  rateLimit:
    average: 600
    burst: 1200
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: compress
  namespace: opencloud
spec:
  compress: {}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: public-chain
  namespace: opencloud
spec:
  chain:
    middlewares:
    - name: crowdsec-bouncer
      namespace: crowdsec
    - name: security-headers
    - name: rate-limit
    - name: compress
