apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: alloy-security
  namespace: alloy
spec:
  endpointSelector:
    matchLabels: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            "io.kubernetes.pod.namespace": alloy
  egress:
    - toEndpoints:
        - matchLabels:
            "io.kubernetes.pod.namespace": kube-system
            "k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    - toEntities:
        - kube-apiserver
    - toEndpoints:
        - matchLabels:
            "io.kubernetes.pod.namespace": loki
      toPorts:
        - ports:
            - port: "3100"
              protocol: TCP
            - port: "80"
              protocol: TCP
            - port: "8080"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            "io.kubernetes.pod.namespace": mimir
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "8080"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            "io.kubernetes.pod.namespace": tempo
      toPorts:
        - ports:
            - port: "4317"
              protocol: TCP
            - port: "4318"
              protocol: TCP
            - port: "3100"
              protocol: TCP
            - port: "80"
              protocol: TCP
            - port: "8080"
              protocol: TCP
