apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: cloudreve
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: cloudreve
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "cloudreve-role"
          serviceAccountRef:
            name: "vault-auth"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudreve-secrets-sync
  namespace: cloudreve
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: cloudreve-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        DB_PASSWORD: "{{ .db_password }}"
        CR_LICENSE_KEY: "{{ .license_key }}"
        conf.ini: |
          [System]
          Mode = master
          Listen = :5212
          Debug = false
          SiteURL = https://drive.foobarbaz.fr

          [Database]
          Type = postgres
          Host = cloudreve-postgres
          Port = 5432
          User = cloudreve
          Password = {{ .db_password }}
          Name = cloudreve
          TablePrefix = cd

          [OIDC]
          Enabled = true
          DisplayName = Keycloak
          Issuer = https://auth.foobarbaz.fr/realms/master
          ClientID = {{ .oidc_client_id }}
          ClientSecret = {{ .oidc_client_secret }}
          Scopes = openid email profile
          UserField = attributes.uid
          EmailField = attributes.securityEmail
          NicknameField = attributes.cn
  data:
    - secretKey: db_password
      remoteRef:
        key: cloudreve-secrets
        property: db-password
    - secretKey: license_key
      remoteRef:
        key: cloudreve-secrets
        property: license-key
    - secretKey: oidc_client_id
      remoteRef:
        key: cloudreve-secrets
        property: oidc-client-id
    - secretKey: oidc_client_secret
      remoteRef:
        key: cloudreve-secrets
        property: oidc-client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudreve-registry-secret-sync
  namespace: cloudreve
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: cloudreve-registry-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"cloudreve.azurecr.io":{"auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}
  data:
    - secretKey: username
      remoteRef:
        key: cloudreve-secrets
        property: username
    - secretKey: password
      remoteRef:
        key: cloudreve-secrets
        property: password
