apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudreve
  namespace: cloudreve
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: cloudreve-public-chain@kubernetescrd
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  rules:
  - host: drive.foobarbaz.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloudreve
            port:
              number: 5212
  tls:
  - hosts:
    - drive.foobarbaz.fr
    secretName: cloudreve-tls
