# Stores segmentés par ServiceAccount
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata: 
  name: ldap-vault-store
  namespace: auth
  annotations: { argocd.argoproj.io/sync-wave: "1" }
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes: 
          mountPath: "kubernetes"
          role: "ldap-role"
          serviceAccountRef: { name: "ldap-sa" }
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata: 
  name: keycloak-vault-store
  namespace: auth
  annotations: { argocd.argoproj.io/sync-wave: "1" }
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes: 
          mountPath: "kubernetes"
          role: "keycloak-role"
          serviceAccountRef: { name: "keycloak-sa" }
---
# Définition des Secrets à générer
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: 
  name: ldap-secrets
  namespace: auth
  annotations: { argocd.argoproj.io/sync-wave: "2" }
spec:
  refreshInterval: "1h"
  secretStoreRef: { name: ldap-vault-store, kind: SecretStore }
  target: { name: ldap-passwords }
  data:
    - secretKey: admin-password
      remoteRef: { key: openldap, property: admin-password }
    - secretKey: jwt-secret
      remoteRef: { key: openldap, property: jwt-secret }
    - secretKey: key-seed
      remoteRef: { key: openldap, property: key-seed }
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: 
  name: keycloak-secrets
  namespace: auth
  annotations: { argocd.argoproj.io/sync-wave: "2" }
spec:
  refreshInterval: "1h"
  secretStoreRef: { name: keycloak-vault-store, kind: SecretStore }
  target: { name: keycloak-passwords }
  data:
    - secretKey: admin-password
      remoteRef: { key: keycloak, property: admin-password }
    - secretKey: db-password
      remoteRef: { key: keycloak, property: keycloak-db-pass }