apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storage.yaml
  - openldap.yaml
  - keycloak-db.yaml
  - keycloak-app.yaml
  - external-secrets.yaml
  - ingress.yaml

labels:
  app.kubernetes.io/part-of: iam-stack