apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy-hubble
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy-hubble
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy-hubble
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
          args:
            - --provider=oidc
            - --oidc-issuer-url=https://auth.foobarbaz.fr/realms/master
            - --email-domain=*
            - --http-address=0.0.0.0:4180
            - --upstream=http://hubble-ui.kube-system.svc.cluster.local:80
            - --cookie-secure=true
            - --cookie-samesite=lax
            - --set-authorization-header=true
            - --pass-access-token=true
            - --redirect-url=https://hubble.foobarbaz.fr/oauth2/callback
            - --insecure-oidc-skip-issuer-verification=true
            - --reverse-proxy=true
            - --allowed-group=cilium-admin
            - --scope=openid profile email groups
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-hubble
                  key: client-id
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-hubble
                  key: client-secret
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-hubble
                  key: cookie-secret
          ports:
            - containerPort: 4180
