# ExternalSecret for OAuth2 Proxy using global ClusterSecretStore
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hubble-oauth2-proxy-secrets
  namespace: hubble
  annotations: { argocd.argoproj.io/sync-wave: "-7" }
spec:
  refreshInterval: "15s"
  secretStoreRef: { name: vault-backend, kind: ClusterSecretStore }
  target:
    name: oauth2-proxy-hubble
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client-id
      remoteRef:
        key: oauth2-proxy
        property: client_id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: client-secret
      remoteRef:
        key: oauth2-proxy
        property: client_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: cookie-secret
      remoteRef:
        key: oauth2-proxy
        property: cookie_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
