apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-hubble
  namespace: kube-system
  annotations: { argocd.argoproj.io/sync-wave: "-7" }
spec:
  refreshInterval: "15s"
  secretStoreRef: { name: vault-backend, kind: ClusterSecretStore }
  target:
    name: oauth2-proxy-hubble
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client-id
      remoteRef: { key: oauth2-proxy, property: client_id }
    - secretKey: client-secret
      remoteRef: { key: oauth2-proxy, property: client_secret }
    - secretKey: cookie-secret
      remoteRef: { key: oauth2-proxy, property: cookie_secret }
