apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: oauth2-proxy-hubble-policy
  namespace: hubble
spec:
  endpointSelector:
    matchLabels:
      k8s-app: oauth2-proxy-hubble
  ingress:
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": traefik
            "k8s:app.kubernetes.io/name": traefik
      toPorts:
        - ports:
            - port: "4180"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": hubble
            "k8s:k8s-app": hubble-ui
      toPorts:
        - ports:
            - port: "8081"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
