apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: oauth2-proxy-hubble-policy
  namespace: hubble
spec:
  endpointSelector:
    matchLabels:
      k8s-app: oauth2-proxy-hubble
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: traefik
      toPorts:
        - ports:
            - port: "4180"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s-app": hubble-ui
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
    - toEntities:
        - kube-apiserver
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
