resources:
  - namespace.yaml
  - storage.yaml
  - external-secrets.yaml
  - baseline-network-policy.yaml
  - policy.yaml
  - release.yaml
  - falco-dashboard-configmap.yaml
  - ingress.yaml
  - edge-middlewares.yaml
