apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: grafana-security
  namespace: grafana
spec:
  endpointSelector:
    matchLabels: {} # S'applique à tous les pods du namespace grafana (Grafana + ACME Solvers)
  ingress:
    # 1. Autoriser Traefik vers Grafana UI (3000) et ACME Solver (8089)
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": traefik
            "app.kubernetes.io/name": traefik
      toPorts:
        - ports:
            - port: "3000"
              protocol: TCP
            - port: "8089"
              protocol: TCP
    # 2. Autoriser le trafic interne au namespace
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": grafana

  egress:
    # 1. DNS Resolution
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    # 2. Kubernetes API access
    - toEntities:
        - kube-apiserver
    # 3. Vault for Secrets
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": vault
      toPorts:
        - ports:
            - port: "8200"
              protocol: TCP
    # 4. Access to World (for updates and plugins)
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
