apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: default
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    chart: vault
    targetRevision: 0.29.0
    helm:
      values: |
        global:
          enabled: true
          namespace: vault
        server:
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 256Mi
              cpu: 250m
          statefulSet:
            securityContext:
              pod:
                runAsUser: 9058
                runAsGroup: 9058
                fsGroup: 9058
                runAsNonRoot: true
              container:
                runAsUser: 9058
                runAsGroup: 9058
                runAsNonRoot: true
          ha:
            enabled: false
          dataStorage:
            enabled: true
            size: 10Gi
            storageClass: "truenas-nfs"
            mountPath: "/vault/data"
          standalone:
            enabled: true
            config: |
              ui = true
              listener "tcp" {
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
              }
              storage "raft" {
                path = "/vault/data"
              }
          ingress:
            enabled: true
            ingressClassName: "traefik"
            hosts:
              - host: "vault.foobarbaz.fr"
            tls:
              - secretName: vault-tls-cert
                hosts:
                  - "vault.foobarbaz.fr"
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
        injector:
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 256Mi
              cpu: 250m
          securityContext:
            pod:
              runAsUser: 9058
              runAsGroup: 9058
              fsGroup: 9058
              runAsNonRoot: true
            container:
              runAsUser: 9058
              runAsGroup: 9058
              runAsNonRoot: true
        ui:
          enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
