apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: pass
  annotations: { argocd.argoproj.io/sync-wave: "-5" }
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: pass
  annotations: { argocd.argoproj.io/sync-wave: "-2" }
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "vaultwarden-role"
          serviceAccountRef: { name: "vault-auth" }
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-secrets-sync
  namespace: pass
  annotations: { argocd.argoproj.io/sync-wave: "0" }
spec:
  refreshInterval: "1h"
  secretStoreRef: { name: vault-backend, kind: SecretStore }
  target:
    name: vaultwarden-passwords
    creationPolicy: Owner
  data:
    - secretKey: admin-token
      remoteRef: { key: vaultwarden, property: password }