apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy-oauth2-proxy
  namespace: notifications
  labels:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/instance: ntfy-oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oauth2-proxy
      app.kubernetes.io/instance: ntfy-oauth2-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oauth2-proxy
        app.kubernetes.io/instance: ntfy-oauth2-proxy
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
          args:
            - --provider=keycloak-oidc
            - --oidc-issuer-url=https://auth.foobarbaz.fr/realms/master
            - --email-domain=*
            - --http-address=0.0.0.0:4180
            - --upstream=static://202
            - --reverse-proxy=true
            - --set-xauthrequest=true
            - --cookie-domain=.foobarbaz.fr
            - --whitelist-domain=.foobarbaz.fr
            - --cookie-secure=true
            - --cookie-httponly=true
            - --cookie-samesite=lax
            - --session-store-type=cookie
            - --redirect-url=https://ntfy.foobarbaz.fr/oauth2/callback
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: ntfy-oauth2-proxy-creds
                  key: client-id
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ntfy-oauth2-proxy-creds
                  key: client-secret
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: ntfy-oauth2-proxy-creds
                  key: cookie-secret
          ports:
            - containerPort: 4180
              name: http
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ntfy-oauth2-proxy
  namespace: notifications
  labels:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/instance: ntfy-oauth2-proxy
spec:
  selector:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/instance: ntfy-oauth2-proxy
  ports:
    - name: http
      port: 80
      targetPort: 4180
