apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ntfy-oauth2-proxy-auth
  namespace: notifications
spec:
  forwardAuth:
    address: http://ntfy-oauth2-proxy.notifications.svc.cluster.local:4180/oauth2/auth
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - X-Auth-Request-Access-Token
      - Authorization
