apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    chart: traefik
    repoURL: ghcr.io/traefik/helm
    targetRevision: 41.0.1
    helm:
      values: |
        providers:
          kubernetesCRD:
            allowCrossNamespace: true
        experimental:
          plugins:
            crowdsec-bouncer:
              moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
              version: v1.7.1
        service:
          type: LoadBalancer
          annotations:
            metallb.io/loadBalancerIPs: "10.0.50.200"
        deployment:
          podSecurityContext:
            fsGroup: 65532
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532
          runAsGroup: 65532
        ingressClass:
          enabled: true
          isDefaultClass: true
        ports:
          web:
            exposedPort: 80
            allowACMEByPass: true
            http:
              redirections:
                entryPoint:
                  to: websecure
                  scheme: https
                  permanent: true
          websecure:
            exposedPort: 443
        log:
          level: INFO
        accessLog:
          enabled: true
          format: json
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
