# 1. Identité pour Vault
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: excalidraw
---
# 2. SecretStore pour Excalidraw
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: excalidraw
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "excalidraw-role"
          serviceAccountRef:
            name: "vault-auth"
---
# 3. Synchronisation des identifiants OAuth2 Proxy
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: excalidraw-oauth2-proxy-creds
  namespace: excalidraw
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: excalidraw-oauth2-proxy-creds
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: excalidraw
        property: client_secret
    - secretKey: cookie-secret
      remoteRef:
        key: excalidraw
        property: cookie_secret
