apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-system
  - 01-system/falco/falco-app-definition.yaml
  - 02-iam/keycloak-app-definition.yaml
  - 03-apps/vaultwarden/vaultwarden-app-definition.yaml
  - 03-apps/blog/blog-app-definition.yaml
  - 03-apps/immich
  - 03-apps/pdf

