apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-system
  - 01-system/falco/falco-app-definition.yaml
  - 02-iam/keycloak-app-definition.yaml
  - 03-apps/vaultwarden/vaultwarden-app-definition.yaml
  - 03-apps/blog/blog-app-definition.yaml
  - 03-apps/poll/poll-app-definition.yaml
  - 03-apps/notifications/notifications-app-definition.yaml
  - 03-apps/cloudreve-app-definition.yaml
  - 03-apps/memos-app-definition.yaml
  - 03-apps/miniflux-app-definition.yaml
  - 03-apps/n8n-app-definition.yaml
  - 03-apps/kutt-app-definition.yaml
  - 03-apps/jellyfin-app-definition.yaml
  - 03-apps/jellyseerr-app-definition.yaml
  - 03-apps/radicale-app-definition.yaml
  - 03-apps/startpage-app-definition.yaml
  - 03-apps/navidrome/navidrome-app-definition.yaml
  - 03-apps/ai/ai-app-definition.yaml
  - 03-apps/immich
  - 03-apps/pingvin-share
  - 03-apps/sure
  - 03-apps/linkwarden-app-definition.yaml
