apiVersion: v1
kind: Service
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  selector:
    app: stirling-pdf
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stirling-pdf
  template:
    metadata:
      labels:
        app: stirling-pdf
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 5930
        fsGroup: 5930
      initContainers:
        - name: init-setup
          image: stirlingtools/stirling-pdf:2.10.1
          command: ["sh", "-c", "mkdir -p /tmp/stirling-pdf && chown -R 5930:5930 /tmp/stirling-pdf"]
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      containers:
        - name: stirling-pdf
          image: stirlingtools/stirling-pdf:2.10.1
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SERVER_FORWARD_HEADERS_STRATEGY
              value: "native"
            - name: SYSTEM_BACKENDURL
              value: "https://pdf.foobarbaz.fr"
            - name: SECURITY_ENABLELOGIN
              value: "false"
            - name: HOME
              value: "/tmp"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stirling-pdf-ingress
  namespace: stirling-pdf
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - pdf.foobarbaz.fr
      secretName: stirling-pdf-tls
  rules:
    - host: "pdf.foobarbaz.fr"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stirling-pdf
                port:
                  number: 80
