apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirling-pdf
  namespace: pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stirling-pdf
  template:
    metadata:
      labels:
        app: stirling-pdf
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - stirling-pdf
                topologyKey: kubernetes.io/hostname
      tolerations:
        - key: "node.kubernetes.io/disk-pressure"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node.kubernetes.io/disk-pressure"
          operator: "Exists"
          effect: "NoExecute"
      securityContext:
        runAsNonRoot: true
        runAsUser: 13042
        runAsGroup: 13042
        fsGroup: 13042
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: stirling-pdf
          image: stirlingtools/stirling-pdf:2.10.1
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SERVER_FORWARD_HEADERS_STRATEGY
              value: "native"
            - name: SYSTEM_BACKENDURL
              value: "https://pdf.foobarbaz.fr"
            - name: SECURITY_ENABLELOGIN
              value: "false"
            - name: HOME
              value: "/tmp"
            - name: DOCKER_ENABLE_CHOWN
              value: "false"
            - name: PUID
              value: "13042"
            - name: PGID
              value: "13042"
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: logs-volume
              mountPath: /logs
            - name: configs-volume
              mountPath: /configs
            - name: pipeline-volume
              mountPath: /pipeline
            - name: custom-files-volume
              mountPath: /customFiles
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 13042
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: logs-volume
          emptyDir: {}
        - name: configs-volume
          emptyDir: {}
        - name: pipeline-volume
          emptyDir: {}
        - name: custom-files-volume
          emptyDir: {}
