apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-webhook-ovh:domain-solver
rules:
  - apiGroups:
      - acme.foobarbaz.fr
    resources:
      - '*'
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-ovh:domain-solver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-ovh:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-release
    namespace: cert-manager
