apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: hubble
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: hubble
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "hubble-role"
          serviceAccountRef:
            name: "vault-auth"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hubble-oauth2-proxy-creds
  namespace: hubble
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: hubble-oauth2-proxy-creds
    creationPolicy: Owner
  data:
    - secretKey: cookie-secret
      remoteRef:
        key: hubble-oauth2-proxy
        property: cookie_secret
    - secretKey: client-secret
      remoteRef:
        key: hubble-oauth2-proxy
        property: client_secret
