apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: hubble-stack-policy
  namespace: hubble
spec:
  endpointSelector: {} # Appliqué à tout le namespace hubble
  ingress:
    # 1. Autoriser Traefik vers le Proxy OAuth2
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": traefik
            "app.kubernetes.io/name": traefik
      toPorts:
        - ports:
            - port: "4180"
              protocol: TCP
    # 2. Autoriser le Proxy vers l'UI
    - fromEndpoints:
        - matchLabels:
            k8s-app: oauth2-proxy-hubble
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    # 3. Autoriser l'UI vers le Relay
    - fromEndpoints:
        - matchLabels:
            k8s-app: hubble-ui
      toPorts:
        - ports:
            - port: "4245"
              protocol: TCP

  egress:
    # 1. Autoriser tout le namespace à contacter le DNS
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
    # 2. Autoriser le Relay vers les agents Cilium (kube-system)
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s-app": cilium
      toPorts:
        - ports:
            - port: "4244"
              protocol: TCP
    # 3. Autoriser l'authentification vers Keycloak (monde extérieur/auth.foobarbaz.fr)
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    # 4. Autoriser Hubble UI vers Kubernetes API
    - toEntities:
        - kube-apiserver
