apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: hubble-stack-policy
  namespace: hubble
spec:
  endpointSelector: {} # Appliqué à tout le namespace hubble
  ingress:
    # 1. Autoriser Traefik vers l'UI Hubble
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: traefik
            app.kubernetes.io/name: traefik
      toPorts:
        - ports:
            - port: "8081"
              protocol: TCP

  egress:
    # 1. Autoriser tout le namespace à contacter le DNS
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
    # 2. Autoriser Hubble UI vers le Relay dans kube-system
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: hubble-relay
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
    # 3. Autoriser Hubble UI vers Kubernetes API
    - toEntities:
        - kube-apiserver
