apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-scrapper-db-worker
  namespace: finance-scrapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-scrapper-db-worker
  template:
    metadata:
      labels:
        app: finance-scrapper-db-worker
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 29097
        runAsGroup: 29097
        fsGroup: 29097
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: db-worker
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 29097
            runAsGroup: 29097
          image: ghcr.io/ripitchip/finance-scrapper-backend:sha-60655f3
          imagePullPolicy: IfNotPresent
          command: ["python"]
          args: ["-m", "app.db_worker"]
          # We'll set the environment variables first.
          env:
            - name: DATA_DIR
              value: "/data"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: finance-scrapper-secrets
                  key: DATABASE_URL
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: finance-scrapper-secrets
                  key: RABBITMQ_URL
            - name: RABBITMQ_QUEUE
              value: "finance-advisor.imports"
            - name: RABBITMQ_PERSISTENCE_QUEUE
              value: "finance-advisor.persistence"
          resources:
            limits:
              cpu: 500m
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
            - name: shared-data
              mountPath: /data
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: finance-scrapper-data-pvc
