apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: finance-scrapper
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: finance-scrapper
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "finance-scrapper-role"
          serviceAccountRef:
            name: "vault-auth"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: finance-scrapper-secrets-sync
  namespace: finance-scrapper
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: finance-scrapper-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        APP_SECRET_KEY: "{{ .app_secret_key }}"
        OIDC_CLIENT_SECRET: "{{ .oidc_client_secret }}"
        POSTGRES_PASSWORD: "{{ .db_password }}"
        RABBITMQ_DEFAULT_PASS: "{{ .rabbitmq_password }}"
        DATABASE_URL: "postgresql+psycopg://advisor:{{ .db_password }}@finance-scrapper-db:5432/advisor"
        RABBITMQ_URL: "amqp://advisor:{{ .rabbitmq_password }}@finance-scrapper-rabbitmq:5672/"
        email_morningstar: "{{ .email_morningstar }}"
        password_morningstar: "{{ .password_morningstar }}"
  data:
    - secretKey: app_secret_key
      remoteRef:
        key: finance-scrapper
        property: app-secret-key
    - secretKey: oidc_client_secret
      remoteRef:
        key: finance-scrapper
        property: oidc-client-secret
    - secretKey: db_password
      remoteRef:
        key: finance-scrapper
        property: db-password
    - secretKey: rabbitmq_password
      remoteRef:
        key: finance-scrapper
        property: rabbitmq-password
    - secretKey: email_morningstar
      remoteRef:
        key: finance-scrapper
        property: email-morningstar
    - secretKey: password_morningstar
      remoteRef:
        key: finance-scrapper
        property: password-morningstar
