apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-scrapper-scraper-worker
  namespace: finance-scrapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-scrapper-scraper-worker
  template:
    metadata:
      labels:
        app: finance-scrapper-scraper-worker
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 29097
        runAsGroup: 29097
        fsGroup: 29097
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: scraper-worker
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 29097
            runAsGroup: 29097
          image: ghcr.io/ripitchip/finance-scrapper-scraper:sha-60655f3
          imagePullPolicy: IfNotPresent
          command: ["python"]
          args: ["-m", "app.worker"]
          env:
            - name: SCRAPER_HEADLESS
              value: "true"
            - name: SCRAPER_TIMEOUT_SECONDS
              value: "30"
            - name: SCRAPER_WORKERS
              value: "10"
            - name: DATA_DIR
              value: "/data"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: finance-scrapper-secrets
                  key: DATABASE_URL
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: finance-scrapper-secrets
                  key: RABBITMQ_URL
            - name: email_morningstar
              valueFrom:
                secretKeyRef:
                  name: finance-scrapper-secrets
                  key: email_morningstar
            - name: password_morningstar
              valueFrom:
                secretKeyRef:
                  name: finance-scrapper-secrets
                  key: password_morningstar
          resources:
            limits:
              cpu: "4"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 1Gi
          volumeMounts:
            - name: shared-data
              mountPath: /data
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: finance-scrapper-data-pvc
