apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/namespace.yaml
  - manifests/storage.yaml
  - manifests/external-secrets.yaml
  - manifests/policy.yaml
  - manifests/app.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: falco-stack
    includeSelectors: true
