apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    chart: falco
    repoURL: https://falcosecurity.github.io/charts
    targetRevision: 8.0.3
    helm:
      values: |
        driver:
          kind: modern_ebpf
        falco:
          json_output: true
          stdout_output: { enabled: true }
          log_level: info
        resources:
          requests: { cpu: 150m, memory: 512Mi }
          limits: { cpu: 1000m, memory: 1024Mi }
        tolerations:
          - { effect: NoSchedule, key: node-role.kubernetes.io/master }
          - { effect: NoSchedule, key: node-role.kubernetes.io/control-plane }
        falcosidekick:
          enabled: true
          webui:
            enabled: true
            # Utilisation du secret généré par ExternalSecret (Vault)
            existingSecret: "falco-ui-secrets"
            user: "admin" # Doit correspondre à la clé admin-user dans Vault
            password: "" # Laissé vide car existingSecret est utilisé
            redis:
              storage:
                enabled: true
                existingClaim: "falco-redis-pvc-static"
            ingress:
              enabled: true
              ingressClassName: traefik
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                traefik.ingress.kubernetes.io/router.tls: "true"
              hosts:
                - host: falco.foobarbaz.fr
                  paths: [{ path: /, pathType: Prefix }]
              tls:
                - { secretName: falco-ui-tls, hosts: [falco.foobarbaz.fr] }
        customRules:
          production-security.yaml: |-
            - rule: Interactive Shell Spawned in Container
              desc: Detects interactive shells in sensitive namespaces
              condition: spawned_process and container and (k8s.ns.name in (vault, keycloak, 01-system, 02-iam, 03-apps)) and proc.name in (shell_procs)
              output: "Interactive shell spawned (user=%user.name pod=%k8s.pod.name ns=%k8s.ns.name cmd=%proc.cmdline)"
              priority: NOTICE
            - rule: Package Management Activity in Pod
              desc: Detects package manager execution inside a container
              condition: spawned_process and proc.name in (package_mgmt_binaries) and container.id != "host" and k8s.pod.name != "<NA>"
              output: "CRITICAL: Package manager execution in POD (user=%user.name pod=%k8s.pod.name cmd=%proc.cmdline)"
              priority: CRITICAL
  destination:
    server: "https://kubernetes.default.svc"
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
