# 1. ServiceAccount for Vault Auth
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: falco
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
---
# 2. SecretStore pointing to Vault
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: falco
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "falco-role"
          serviceAccountRef:
            name: "vault-auth"
---
# 3. Synchronize Falcosidekick Secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: falco-secrets-sync
  namespace: falco
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: falco-ui-secrets
    creationPolicy: Owner
    template:
      data:
        FALCOSIDEKICK_UI_USER: "{{ .user }}:{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: falco
        property: admin_password
    - secretKey: user
      remoteRef:
        key: falco
        property: admin_user
