apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ntfy-ui-protected
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Middleware OAuth2 Proxy
    # traefik.ingress.kubernetes.io/router.middlewares: default-oauth2-proxy@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ntfy.foobarbaz.fr
      secretName: ntfy-tls
  rules:
    - host: ntfy.foobarbaz.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ntfy
                port:
                  number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ntfy-api-bypass
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    # Priorite haute pour contourner OAuth2
    traefik.ingress.kubernetes.io/router.priority: "100"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ntfy.foobarbaz.fr
      secretName: ntfy-tls
  rules:
    - host: ntfy.foobarbaz.fr
      http:
        paths:
          # API pour l application mobile Ntfy
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: ntfy
                port:
                  number: 80
          # Topic specifique pour Android
          - path: /alertes-cluster
            pathType: Prefix
            backend:
              service:
                name: ntfy
                port:
                  number: 80
