apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ntfy-protected
  namespace: notifications
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Middleware d'authentification pour l'interface utilisateur
    traefik.ingress.kubernetes.io/router.middlewares: notifications-ntfy-oauth2-proxy-auth@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ntfy.foobarbaz.fr
      secretName: ntfy-tls
  rules:
    - host: ntfy.foobarbaz.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ntfy
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ntfy-public
  namespace: notifications
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    # Priorité élevée pour court-circuiter l'authentification sur les endpoints publics
    traefik.ingress.kubernetes.io/router.priority: "100"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ntfy.foobarbaz.fr
      secretName: ntfy-tls
  rules:
    - host: ntfy.foobarbaz.fr
      http:
        paths:
          # Endpoint pour OAuth2 Proxy (Nécessaire pour le callback)
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: ntfy-oauth2-proxy
                port:
                  number: 80
          # API pour l'application mobile (Bypass Auth)
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: ntfy
                port:
                  number: 80
          # Topic d'alertes (Bypass Auth)
          - path: /alertes-cluster
            pathType: Prefix
            backend:
              service:
                name: ntfy
                port:
                  number: 80
