apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ntfy
  namespace: notifications
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ntfy.foobarbaz.fr
      secretName: ntfy-tls
  rules:
    - host: ntfy.foobarbaz.fr
      http:
        paths:
          # API Bypass (Application mobile et alertes cluster)
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: ntfy
                port:
                  number: 80
          - path: /alertes-cluster
            pathType: Prefix
            backend:
              service:
                name: ntfy
                port:
                  number: 80
          # Tout le reste (UI) passe par OAuth2 Proxy qui redirige vers ntfy après auth
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ntfy-oauth2-proxy
                port:
                  number: 4180
